### ISSUE TITLE
Reference an issue in your Pull Request

### ISSUE THREAD

**Issue by duckRabbitPy** [jimmycooney94/blackjackJs#2]
If you find a bug or have an improvement in mind, you can make a new issue. 

Then in your Pull request you can use `fixes` and # sign to reference an issue to show it is fixed, this will automatically close the issue on merge.

So to close this issue, write `fixes #2`  in your pull request. When you merge the PR this issue will be closed!

https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue

**Comment by jimmycooney94** [comment]
Ty for the tip...have added some more issues and will use this to manage them!
